### ISSUE TITLE
Threadpool comment

### ISSUE THREAD

**Issue by leon-barrett** [jakepearson/quickie#14]
Hi. I am the author of Claypoole, and a friend pointed out that you're using it. That's great, and I'm super excited, so I had to check out your project! In looking at your usage, I noticed a minor point that might help improve your thread usage.

Alas, threadpools in Java aren't automatically garbage collected. In [runner.clj](https://github.com/jakepearson/quickie/blob/d279a1c08f5c91120bcc4f2580b3ddb1de650c5e/src/quickie/runner.clj#L170), you create a threadpool but don't shut it down. That could potentially leak threads, leading to a growing number of threads sitting around. It's likely not an issue, as those threads go away when the process stops, but it could trip you up in a long-running process.

Instead of explicitly allocating the pool, you can just specify the pool size when using `upmap`. Then, an appropriately-sized pool [will be allocated and cleaned up automatically](https://github.com/TheClimateCorporation/claypoole#do-i-really-need-to-manage-all-those-threadpools).

```
(let [...
      results (->> test-nses
                   (threadpool/upmap 20 ...)
                   ...)
      ...]
  ...)
```

**Comment by jakepearson** [comment]
Thanks for the tip, added.
