### ISSUE TITLE
portable clojure cljc files don't trigger re-run

### ISSUE THREAD

**Issue by stevebuik** [jakepearson/quickie#17]
Changes in core.cljc in src or in test dirs are not noticed by quickie.

Happy to provide a test case although it's pretty simple. Just use a lein new project and rename core.clj and core-test.clj.

**Comment by stevebuik** [comment]
Looks like lein test has a similar issue. https://github.com/technomancy/leiningen/issues/1940

I wonder if it's the same issue in both cases

**Comment by jakepearson** [comment]
All set and deployed at 0.4.2. Thanks for the :pr:

**Comment by ftravers** [comment]
regressed?  I'm seeing this still.

╭─fenton@ss9 ~/projects/pc-message  ‹master› 
╰─➤  lein quickie
:reloading (pc.api-test)
Ran 0 tests containing 0 assertions.
   All Tests Passing!  
^C%                                                                                                                      ╭─fenton@ss9 ~/projects/pc-message  ‹master› 
╰─➤  lein test                                                                                                     130 ↵

lein test pc.api-test

lein test :only pc.api-test/base

FAIL in (base) (api_test.clj:9)
base
expected: (= 1 "A")
  actual: (not (= 1 "A"))

 :source-paths ["src/cljc"]

  :plugins [[quickie "0.4.2"]]

  :dependencies [[org.clojure/clojure "1.9.0-alpha5"]
                 [org.clojure/clojurescript "1.9.36"]]
